#!/usr/bin/env bash

EXTERNAL_OUTPUT="DP-2-1"
INTERNAL_OUTPUT="eDP-1"
STATE_FILE="/tmp/monitor_mode_$USER.dat"

# if we don't have a file, start at zero
if [ ! -f $STATE_FILE ] ; then
    monitor_mode="all"
else
    # otherwise read the value from the file
    monitor_mode=$(cat $STATE_FILE)
fi

if [ $monitor_mode = "all" ]; then
    monitor_mode="EXTERNAL"
    echo "Switching to EXTERNAL ($EXTERNAL_OUTPUT only)"
    xrandr --output $INTERNAL_OUTPUT --off --output $EXTERNAL_OUTPUT --auto
elif [ $monitor_mode = "EXTERNAL" ]; then
    monitor_mode="INTERNAL"
    echo "Switching to INTERNAL ($INTERNAL_OUTPUT only)"
    xrandr --output $INTERNAL_OUTPUT --auto --output $EXTERNAL_OUTPUT --off
elif [ $monitor_mode = "INTERNAL" ]; then
    monitor_mode="CLONE"
    echo "Switching to CLONE ($INTERNAL_OUTPUT and $EXTERNAL_OUTPUT duplicated)"
    xrandr --output $INTERNAL_OUTPUT --auto --output $EXTERNAL_OUTPUT --auto --same-as $INTERNAL_OUTPUT
else
    monitor_mode="all"
    echo "Switching to ALL ($INTERNAL_OUTPUT and $EXTERNAL_OUTPUT as separately)"
    xrandr --output $INTERNAL_OUTPUT --auto --output $EXTERNAL_OUTPUT --auto --left-of $INTERNAL_OUTPUT
fi
echo $monitor_mode > $STATE_FILE
